name: roommate
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  design_system:
    path: ../design_system

  iconsax: ^0.0.8
  google_fonts: ^6.2.1
  flutter_modular: ^6.3.3
  flutter_svg: ^2.0.10+1
  flutter_html: ^3.0.0-beta.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/langs/en.json
    - assets/langs/pt.json
    - assets/icons/
